export const SET_NAVIGATION = 'SET_NAVIGATION';
export const SOCIAL_CONNECT_SET = 'SOCIAL_CONNECT_SET';
export const SET_FILTER_DATA_PROP = 'SET_FILTER_DATA_PROP';
export const PUSH_FILTER_DATA_PROP = 'PUSH_FILTER_DATA_PROP';
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_USER_INFO_PROP = 'SET_USER_INFO_PROP';
export const SET_CAPAIGNS_PROP = 'SET_CAPAIGNS_PROP';
export const PUSH_CAMPAIGNS_PROP = 'PUSH_CAMPAIGNS_PROP';
export const SET_COMPANY_PARTICIPANT_PROP = 'SET_COMPANY_PARTICIPANT_PROP';
export const PUSH_COMPANY_PARTICIPANT_PROP = 'PUSH_COMPANY_PARTICIPANT_PROP';
export const SET_COMPANY_PARTICIPANT_LIST_PROP = 'SET_COMPANY_PARTICIPANT_LIST_PROP';
export const PUSH_COMPANY_PARTICIPANT_LIST_PROP = 'PUSH_COMPANY_PARTICIPANT_LIST_PROP';
export const SET_PENDING_PARTICIPANT_PROP = 'SET_PENDING_PARTICIPANT_PROP';
export const PUSH_PENDING_PARTICIPANT_PROP = 'PUSH_PENDING_PARTICIPANT_PROP';
export const SET_COMPANY_PARTICIPANT_TOP10 = 'SET_COMPANY_PARTICIPANT_TOP10';
export const PUSH_COMPANY_PARTICIPANT_TOP10 = 'PUSH_COMPANY_PARTICIPANT_TOP10';
export const SET_COMPANY_PARTICIPANT_TOP10_LIST = 'SET_COMPANY_PARTICIPANT_TOP10_LIST';
export const PUSH_COMPANY_PARTICIPANT_TOP10_LIST = 'PUSH_COMPANY_PARTICIPANT_TOP10_LIST';
export const SET_COMPANY_PARTICIPANT_WINNERS = 'SET_COMPANY_PARTICIPANT_WINNERS';
export const PUSH_COMPANY_PARTICIPANT_WINNERS = 'PUSH_COMPANY_PARTICIPANT_WINNERS';
export const SET_COMMENTS = 'SET_COMMENTS';
export const PUSH_COMMENT = 'PUSH_COMMENT';
export const SET_LIKE_LIST = 'SET_LIKE_LIST';
export const PUSH_LIKE_LIST = 'PUSH_LIKE_LIST';
export const SET_HOME_PROP = 'SET_HOME_PROP';
export const PUSH_HOME_PROP = 'PUSH_HOME_PROP';
export const SET_PROFILE_PROP = 'SET_PROFILE_PROP';
export const PUSH_PROFILE_PROP = 'PUSH_PROFILE_PROP';
export const SET_OTHER_PROFILE_NEWSFEED = 'SET_OTHER_PROFILE_NEWSFEED';
export const SET_OTHER_PROFILE_CONTEST = 'SET_OTHER_PROFILE_CONTEST';
export const SET_OTHER_PROFILE_NEWSFEED_LIST = 'SET_OTHER_PROFILE_NEWSFEED_LIST';
export const PUSH_OTHER_PROFILE_NEWSFEED = 'PUSH_OTHER_PROFILE_NEWSFEED';
export const PUSH_OTHER_PROFILE_CONTEST = 'PUSH_OTHER_PROFILE_CONTEST';
export const PUSH_OTHER_PROFILE_NEWSFEED_LIST = 'PUSH_OTHER_PROFILE_NEWSFEED_LIST';
export const SET_OTHER_PROFILE_USERINFO = 'SET_OTHER_PROFILE_USERINFO';
export const OTHER_SOCIAL_CONNECT_SET = 'OTHER_SOCIAL_CONNECT_SET';
export const SET_PUSH_NOTIFICATIONS = 'SET_PUSH_NOTIFICATIONS';
export const SET_APP_DATA = 'SET_APP_DATA';
export const PUSH_APP_DATA = 'PUSH_APP_DATA';
export const SET_PICS_USER_DATA = 'SET_PICS_USER_DATA';
export const PUSH_PICS_USER_DATA = 'PUSH_PICS_USER_DATA';
export const SET_PICS_VALUE = 'SET_PICS_VALUE';
export const SET_PICS_DATA = 'SET_PICS_DATA';
export const PUSH_PICS_DATA = 'PUSH_PICS_DATA';
export const SET_SUBSCRIBED_LIST = 'SET_SUBSCRIBED_LIST';
export const PUSH_SUBSCRIBED_LIST = 'PUSH_SUBSCRIBED_LIST';
export const SET_SUBSCRIBERS_LIST = 'SET_SUBSCRIBERS_LIST';
export const PUSH_SUBSCRIBERS_LIST = 'PUSH_SUBSCRIBERS_LIST';
export const SET_NOTIFICATIONS_DATA = 'SET_NOTIFICATIONS_DATA';
export const PUSH_NOTIFICATIONS_DATA = 'PUSH_NOTIFICATIONS_DATA';
export const SET_NOTIFICATIONS_PENDING_REQUESTS = 'SET_NOTIFICATIONS_PENDING_REQUESTS';
export const SET_NOTIFICATIONS_LIKE_YOU = 'SET_NOTIFICATIONS_LIKE_YOU';
export const SET_SUBSCRIBE_MESSAGE_DATA = 'SET_SUBSCRIBE_MESSAGE_DATA';
export const PUSH_SUBSCRIBE_MESSAGE_DATA = 'PUSH_SUBSCRIBE_MESSAGE_DATA';
export const SET_USER_MESSSAGES = 'SET_USER_MESSSAGES';
export const PUSH_USER_MESSSAGES = 'PUSH_USER_MESSSAGES';
export const SET_REFRESH_INDICATOR = 'SET_REFRESH_INDICATOR';
export const SET_PROFILE_REFRESH_INDICATOR = 'SET_PROFILE_REFRESH_INDICATOR';
export const SET_OTHER_PROFILE_REFRESH_INDICATOR = 'SET_OTHER_PROFILE_REFRESH_INDICATOR';
export const SET_COMPANY_REFRESH_INDICATOR = 'SET_COMPANY_REFRESH_INDICATOR';
export const SET_COMPANY_LIST_REFRESH_INDICATOR = 'SET_COMPANY_LIST_REFRESH_INDICATOR';
export const SET_PARTICIPANT_TOP10_LIST_REFRESH_INDICATOR = 'SET_PARTICIPANT_TOP10_LIST_REFRESH_INDICATOR';
export const CHANGE_STORY_FLAG = 'CHANGE_STORY_FLAG';
export const CHANGE_STORY_INDEX = 'CHANGE_STORY_INDEX';
export const SET_STORY_REFRESH_INDICATOR = 'SET_STORY_REFRESH_INDICATOR';
export const SET_SINGLE_USER_STORY = 'SET_SINGLE_USER_STORY';

//Pagination
export const SET_PAGINATION_NEWSFEED = 'SET_PAGINATION_NEWSFEED';
export const SET_PAGINATION_OWN_NEWSFEED = 'SET_PAGINATION_OWN_NEWSFEED';
export const SET_PAGINATION_HOME_EXPLORE = 'SET_PAGINATION_HOME_EXPLORE';
export const SET_PAGINATION_HOME_USERS = 'SET_PAGINATION_HOME_USERS';
export const SET_PAGINATION_HOME_PARTICIPANT = 'SET_PAGINATION_HOME_PARTICIPANT';
export const SET_PAGINATION_COMPANY_CAMPAIGN = 'SET_PAGINATION_COMPANY_CAMPAIGN';
export const SET_PAGINATION_CREATOR_CAMPAIGN = 'SET_PAGINATION_CREATOR_CAMPAIGN';
export const SET_PAGINATION_OWN_SAVED = 'SET_PAGINATION_OWN_SAVED';
export const SET_PAGINATION_OWN_CONTEST = 'SET_PAGINATION_OWN_CONTEST';
export const SET_PAGINATION_OTHER_NEWSFEED = 'SET_PAGINATION_OTHER_NEWSFEED';
export const SET_PAGINATION_LIKE_LIST = 'SET_PAGINATION_LIKE_LIST';
export const SET_PAGINATION_NOTIFICATION = 'SET_PAGINATION_NOTIFICATION';
export const SET_PAGINATION_MESSAGE_USERS = 'SET_PAGINATION_MESSAGE_USERS';
export const SET_PAGINATION_SUBSCRIBED_STORY = 'SET_PAGINATION_SUBSCRIBED_STORY';
export const SET_PAGINATION_EXPLORE_STORY = 'SET_PAGINATION_EXPLORE_STORY';
export const ADD_STORY_DATA = 'ADD_STORY_DATA';

//Filter Wrapper
export const SET_FILTER_PROP = 'SET_FILTER_PROP';
export const SET_FILTER_PROP_ARR = 'SET_FILTER_PROP_ARR';
export const RESET_FILTER = 'RESET_FILTER';
export const RESET_FILTER_ARR = 'RESET_FILTER_ARR';

export const COMPANY_SET_FILTER_PROP = 'COMPANY_SET_FILTER_PROP';
export const COMPANY_SET_FILTER_PROP_ARR = 'COMPANY_SET_FILTER_PROP_ARR';
export const COMPANY_RESET_FILTER = 'COMPANY_RESET_FILTER';
export const COMPANY_RESET_FILTER_ARR = 'COMPANY_RESET_FILTER_ARR';

export const HOME_EXPLORE_SET_FILTER_PROP = 'HOME_EXPLORE_SET_FILTER_PROP';
export const HOME_EXPLORE_SET_FILTER_PROP_ARR = 'HOME_EXPLORE_SET_FILTER_PROP_ARR';
export const HOME_EXPLORE_RESET_FILTER = 'HOME_EXPLORE_RESET_FILTER';
export const HOME_EXPLORE_RESET_FILTER_ARR = 'HOME_EXPLORE_RESET_FILTER_ARR';

export const HOME_PARTICIPANT_SET_FILTER_PROP = 'HOME_PARTICIPANT_SET_FILTER_PROP';
export const HOME_PARTICIPANT_SET_FILTER_PROP_ARR = 'HOME_PARTICIPANT_SET_FILTER_PROP_ARR';
export const HOME_PARTICIPANT_RESET_FILTER_ARR = 'HOME_PARTICIPANT_RESET_FILTER_ARR';
export const HOME_PARTICIPANT_RESET_FILTER = 'HOME_PARTICIPANT_RESET_FILTER';

export const HOME_USER_SET_FILTER_PROP = 'HOME_USER_SET_FILTER_PROP';
export const HOME_USER_SET_FILTER_PROP_ARR = 'HOME_USER_SET_FILTER_PROP_ARR';
export const HOME_USER_RESET_FILTER = 'HOME_USER_RESET_FILTER';
export const HOME_USER_RESET_FILTER_ARR = 'HOME_USER_RESET_FILTER_ARR';

export const SUBSCRIBED_STORY_SET_FILTER_PROP = 'SUBSCRIBED_STORY_SET_FILTER_PROP';
export const SUBSCRIBED_STORY_SET_FILTER_PROP_ARR = 'SUBSCRIBED_STORY_SET_FILTER_PROP_ARR';
export const SUBSCRIBED_STORY_RESET_FILTER_ARR = 'SUBSCRIBED_STORY_RESET_FILTER_ARR';
export const SUBSCRIBED_STORY_RESET_FILTER = 'SUBSCRIBED_STORY_RESET_FILTER';

export const EXPLORE_STORY_SET_FILTER_PROP = 'EXPLORE_STORY_SET_FILTER_PROP';
export const EXPLORE_STORY_SET_FILTER_PROP_ARR = 'EXPLORE_STORY_SET_FILTER_PROP_ARR';
export const EXPLORE_STORY_RESET_FILTER_ARR = 'EXPLORE_STORY_RESET_FILTER_ARR';
export const EXPLORE_STORY_RESET_FILTER = 'EXPLORE_STORY_RESET_FILTER';

export const SET_TIMESTAMP_DATA = 'SET_TIMESTAMP_DATA';

//------------------------------------------------------------------------------------------------------
export const RESET_STORE = 'RESET_STORE';
export const SET_TRANSLATION = 'SET_TRANSLATION';
export const SET_LOGIN_DATA = 'SET_LOGIN_DATA';
export const SET_LOGIN_PROP = 'SET_LOGIN_PROP';
export const SET_TASKS = "SET_TASKS";


